### ISSUE TITLE
ukol1

### ISSUE THREAD

**Issue by TerezaZajac** [TerezaZajac/czechitas_PythonProData2023#1]
@M-Kovar tak snad vetsina hotovo :)

**Comment by M-Kovar** [comment]
Ahoj Terezo,

dobrá práce, máš to pěkné, kromě pivot tabulky a pár drobností je tam vše správně, takže píšu splněno:-). Pár komentářů:

- Přidání `previous_winner_party`: Tady je vhodné shiftovat na datech seskupených podle států, protože jinak se třeba poslední výsledek (2020) Alabamy posune k prvnímu (1976) z Aljašky, což nechceme. Pomocí groupby tedy ohraničíme jednotlivé státy: `presidents_winners['previous_winner_party'] = presidents_winners.groupby('state')['party_simplified'].shift(periods=1)`. Podobně je potřeba ohraničit posun později při zpracování dvou nejlepších kandidátů, tedy `presidents_two_best.groupby(["year", "state"])['candidatevotes'].shift(periods=-1)`.

- Funkce `winner_change()`: Tady je to celkem jedno, ale obecně by se mohlo hodit pro rok 1976 vracet jinou hodnotu než 0, aby se rozlišily případy "žádná změna" od "nemáme data, nevíme". Dá se použít třeba prázdná hodnota Not-a-Number (NaN) zapisovaná jako `float('nan')`.

- Výběr dat pro graf: Používáš `presidents_winners_pivot[presidents_winners_pivot['change'] >= 3]`, vyberou se tedy státy s 3 a více změnami, což taky může být. Pokud bys chtěla vybrat prvních třeba 10 států s nejvíce změnami, můžeš jednoduše takto (protože data jsou seřazená): `presidents_winners_pivot.iloc[:10]`, případně dokonce jen `presidents_winners_pivot[:10]`.

- Graf: Jen pro zajímavost, popisky států můžeš natočit pomocí `plt.xticks(rotation=45)`. V tomhle případě to teda kvůli některým dlouhým názvům čitelnosti kdovíjak nepomůže, ale zkrátka je to taky možnost:).

- Pivot tabulka: Vlastně máš celý příkaz dobře a jen místo `columns="change"` potřebujeme `columns="swing"`, protože chceme vědět, kolik států jak swingovalo. Tedy `presidents_pivot = pd.pivot_table(data = presidents_winners, values="state" , index="year" , columns="swing" , aggfunc="count", fill_value=0)`. Super, že jsi použila parametr `fill_value`, který přidáním nul dodává na přehlednosti.

Celkově pěkná práce :-). Kdyby něco nebylo jasné, klidně dořešíme.

**Comment by TerezaZajac** [comment]
Moc diky za pripominky, urcite se je pokusim zapracovat a vylepsit ukol, bohuzel se k tomu dostanu az pristi tyden. Ted budu mit dovolenou (na slack to jeste budu psat).
