### ISSUE TITLE
kontrola ukolu

### ISSUE THREAD

**Issue by TerezaZajac** [TerezaZajac/czechitas_PythonProData2023#3]
prosim o kontrolu :)

**Comment by TerezaZajac** [comment]
hw_02_eurobarametr.py

**Comment by M-Kovar** [comment]
Ahoj Terezo,

moc pěkné, úkol máš zpracovaný pečlivě, testy a jejich výsledky poctivě okomentované, vše perfektně sedí, píšu splněno :-). Jediný komentář, úplná drobnost:

- Formulace hypotéz `Procento lidí, kteří věří EU a procento lidí, kteří věří své národní vládě, jsou statisticky ne/závislé`: "statisticky" by se hodilo nahradit "lineárně", jelikož pearsonem zkoumáme korelaci jakožto lineární vztah, ale v datech by mohl teoreticky být i nelineární vztah, který bychom mohli testovat jinými způsoby. Pro zajímavost, existují i metody pro nelineární korelaci, např. "distance correlation" - podrobnosti neznám, jen jsem si přečetl, že existuje:).

**Comment by TerezaZajac** [comment]
Ahoj, diky za upresneni, ja si tim 'statisticky' taky nebyla jista.
