### ISSUE TITLE
ukol 05

### ISSUE THREAD

**Issue by TerezaZajac** [TerezaZajac/czechitas_PythonProData2023#4]
hw_05_fyzicka_kondice.py

prosim o kontrolu :)

**Comment by M-Kovar** [comment]
Ahoj Terezo,

dobrá práce, postupy máš správně a úkol je splněn. Kromě jednoho obecného komentáře k tomu nic nemám - kdyby Tě něco zajímalo, klidně se ptej.

- Osobně mi vycházející klasifikátory s přesností kolem 50 % teda nepřijdou nic moc a i na confusion matrix je vidět, že čísla mimo diagonálu jsou dost velká, takže spousta vzorků padá do jiných kategorií. Na druhou stranu je zas celkem dobré, že padají často jen o jednu kategorii vedle (pole okolo diagonály), což by v praxi nemuselo znamenat tak velký problém, jako kdyby padaly úplně mimo. Tenhle komentář nemyslím jako výtku, ale jen jako takový postesk nad výsledky:), ač vychází správně. Jako vždycky by ale záleželo na praktické interpretaci a využití - možná by i taková nižší přesnost stačila a byla vyvážená třeba úsporami plynoucími z neprovádění fyzických testů. Kdo ví:).

Tak díky za spolupráci a přeju hodně štěstí i v dalších datových dobrodružstvích:-).
